config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to: 'home#index'

  get 'room_registrations/search', to: 'room_registrations#search'
  get 'room_registrations/search_free_word', to: 'room_registrations#search_free_word'
  get 'room_registrations/post', to: 'room_registrations#post'

  post 'room_bookings/confirm', to: 'room_bookings#confirm' # 確認画面
  post 'room_bookings/back', to: 'room_bookings#back'  # 確認画面から「入力画面に戻る」をクリックしたとき

  resources :room_registrations
  resources :room_bookings
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room_registration.rb
class RoomRegistration < ApplicationRecord
  mount_uploader :room_image, RoomImageUploader
  has_many :room_bookings
  belongs_to :user
end

app/controllers/room_registrations_controller.rb
class RoomRegistrationsController < ApplicationController
  def index
    @room_registrations = RoomRegistration.all
  end

  def new
    @room_registration = RoomRegistration.new
  end

  def create
    @room_registration = RoomRegistration.new(room_registration_params)
    if @room_registration.save
      flash[:notice] = "ルームを新規登録しました"
      redirect_to room_registrations_post_path
    else
      flash[:notice] = "ルームの登録に失敗しました"
      render :new
    end
  end

  def show
    @room_registration = RoomRegistration.find(params[:id])
    @room_booking = RoomBooking.new
  end

  def destroy
    @room_registration = RoomRegistration.find(params[:id])
    @room_registration.destroy
    flash[:notice] = "ルームを削除しました"
    redirect_to room_registrations_path
  end

  def search
    if params[:room_address].present?
      @room_registrations = RoomRegistration.where('room_address LIKE ?', "%#{params[:room_address]}%")
    else
      @room_registrations = RoomRegistration.none
      flash[:notice] = "該当がありませんでした"
    end
    @room_booking = RoomBooking.new
  end

  def search_free_word
    if params[:free_word].present?
      @room_registrations = RoomRegistration.where('room_name LIKE ? OR room_address LIKE ? OR room_introduction LIKE ? OR room_price LIKE ?', "%#{params[:free_word]}%", "%#{params[:free_word]}%", "%#{params[:free_word]}%", "%#{params[:free_word]}%")
    else
      @room_registrations = RoomRegistration.none
      flash[:notice] = "該当がありませんでした"
    end
  end
  
  def post
    @user = current_user
    @room_registrations = @user.room_registrations
  end


  private

  def room_registration_params
    params.require(:room_registration).permit(:id, :room_name, :room_introduction, :room_price, :room_address, :room_image).merge(user_id: current_user.id)
  end
end

app/helpers/room_registrations_helper.rb
module RoomRegistrationsHelper
end

app/views/room_registrations/index.html.erb
<div class="index_container">
  <h2>ルーム情報一覧</h2>
  <div class="rooms">
    <% @room_registrations.each do |room_registration| %>
      <div class="room">
        <div class="id"><%= room_registration.id %></div>
        <div class="room_image"><%= image_tag room_registration.room_image.thumb300.url %></div>
        <div class="room_name"><%= room_registration.room_name %></div>
        <div class="room_address"><%= room_registration.room_address %></div>
        <div class="room_introduction"><%= room_registration.room_introduction %></div>
        <div class="room_price">￥<%= room_registration.room_price %></div>
        <%= link_to "予約", room_registration %>
        <%= link_to "削除", room_registration, method: :delete, data: { confirm: "本当に削除しますか？" } %>
      </div>
    <% end %>
  </div>
</div>
 

app/views/room_registrations/new.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<div class="registration_container">
  <h3>ルーム情報登録</h3>

  <%= form_with model: @room_registration do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <div class="registration">
      <%= f.label :room_name, "ルーム名", class:"bold" %><br>
      <%= f.text_field :room_name, class:"input_field", placeholder: "ルーム名を入力" %>
    </div> 
    <div class="registration">
      <%= f.label :room_introduction, "ルーム紹介", class:"bold" %><br>
      <%= f.text_area :room_introduction, class:"wide_field", placeholder: "ルームの説明を入力" %>
    </div>
    <div class="registration">
      <%= f.label :room_price, "料金", class:"bold" %><br>
      <%= f.number_field :room_price, class:"input_field", placeholder: "１日あたりの料金を入力"  %>
    </div>
    <div class="registration">
      <%= f.label :room_address, "住所", class:"bold" %><br>
      <%= f.text_field :room_address, class:"input_field", placeholder: "住所を入力" %>
    </div>
    <div class="registration">
      <%= f.label :room_image, "ルーム画像", class:"bold" %><br>
      <%= f.file_field :room_image, class:"input_field" %>
    </div>
    <div class="registration">
      <%= f.submit "登録", class: "submit" %>
    </div>
  <% end %>

</div>

app/views/room_registrations/post.html.erb
<div class="booking_container">
  <h3><%= current_user.name %>さん のルーム登録情報一覧</h3>

  <div class="booking_table">
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>ルーム画像</th>
          <th>ルーム名</th>
          <th>ルーム紹介</th>
          <th>金額</th>
          <th>登録日時</th>
        </tr>
      </thead>
      <% @room_registrations.each do |room_registration| %>
      <tbody>
        <tr>
          <td><%= image_tag room_registration.room_image.thumb300.url %></td>
          <td><%= room_registration.room_name %></td>
          <td><%= room_registration.room_introduction %></td>
          <td><%= room_registration.room_price %></td>
          <td><%= room_registration.created_at %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/room_registrations/search.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<h3>検索結果</h3>
<div class="booking_table">
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>所在地</th>
        <th>紹介</th>
        <th>金額</th>
        <th>予約</th>
      </tr>
    </thead>
    <tbody>
    <% @room_registrations.each do |room_registration| %>
      <tr="rooms">
        <td><%= image_tag room_registration.room_image.thumb300.url %></td>>
        <td><%= room_registration.room_name %></td>>
        <td><%= room_registration.room_address %></td>>
        <td><%= room_registration.room_introduction %></td>>
        <td>￥<%= room_registration.room_price %></td>>
        <td><%= link_to "予約へ", room_registration %></td>>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/room_registrations/search_free_word.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<h3>検索結果</h3>
<div class="booking_table">
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>所在地</th>
        <th>紹介</th>
        <th>金額</th>
        <th>予約</th>
      </tr>
    </thead>
    <tbody>
    <% @room_registrations.each do |room_registration| %>
      <tr="rooms">
        <td><%= image_tag room_registration.room_image.thumb300.url %></td>>
        <td><%= room_registration.room_name %></td>>
        <td><%= room_registration.room_address %></td>>
        <td><%= room_registration.room_introduction %></td>>
        <td>￥<%= room_registration.room_price %></td>>
        <td><%= link_to "予約へ", room_registration %></td>>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/room_registrations/show.html.erb
<div class="booking_container">
  <h3>予約ページ</h3>
 
  <%= form_with model: @room_booking, url: room_bookings_confirm_path do |f| %>

    <p><%= f.hidden_field :room_registration_id, value: @room_registration.id %></p>
    <p><%= f.hidden_field :user_id, value: current_user.id %></p>
    <div class="booking">
      <%= f.label :start_date, "開始日", class:"bold" %><br>
      <%= f.date_field :start_date, class:"input_field" %>
    </div> 
    <div class="booking">
      <%= f.label :end_date, "終了日", class:"bold" %><br>
      <%= f.date_field :end_date, class:"input_field" %>
    </div>
    <div class="booking">
      <%= f.label :number_of_people, "人数", class:"bold" %><br>
      <%= f.number_field :number_of_people, class:"input_field", placeholder: "宿泊人数を入力"  %>
    </div>
    <div class="booking">
      <div><%= f.submit "確認画面へ", class: "submit" %></div>
      <button type="button", class="btn btn-success"><%= link_to "ルーム情報一覧へ", room_registrations_path %></button>
    </div>
  <% end %>

</div>