config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to: 'home#index'

  get 'room_registrations/search', to: 'room_registrations#search'
  get 'room_registrations/search_free_word', to: 'room_registrations#search_free_word'
  get 'room_registrations/post', to: 'room_registrations#post'

  post 'room_bookings/confirm', to: 'room_bookings#confirm' # 確認画面
  post 'room_bookings/back', to: 'room_bookings#back'  # 確認画面から「入力画面に戻る」をクリックしたとき

  resources :room_registrations
  resources :room_bookings
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room_booking.rb
class RoomBooking < ApplicationRecord
  belongs_to :user
  belongs_to :room_registration
end

app/controllers/room_bookings_controller.rb
class RoomBookingsController < ApplicationController
  def index
    @room_bookings = RoomBooking.all
    @user = current_user
  end
  
  def confirm
    @room_booking = RoomBooking.new(room_booking_params)
    @booking_days = (@room_booking.end_date - @room_booking.start_date).to_i
  end

  def create
    @room_booking = RoomBooking.new(room_booking_params)
    @booking_days = (@room_booking.end_date - @room_booking.start_date).to_i
    if @room_booking.save
      flash[:notice] = "予約が完了しました"
    else
      flash[:notice] = "予約が失敗しました"
      render "confirm"
    end
  end

  def show
    @user = current_user
    @room_bookings = @user.room_bookings
  end

  private

  def room_booking_params
    params.require(:room_booking).permit(:start_date, :end_date, :number_of_people).merge(user_id: current_user.id, room_registration_id: params[:room_booking][:room_registration_id])
  end

end

app/helpers/room_bookings_helper.rb
module RoomBookingsHelper
end

app/views/room_bookings/back.html.erb
<div class="booking_container">
  <h3>予約ページ</h3>

  <%= form_with model: @room_booking do |f| %>

  <p><%= f.hidden_field :room_registration_id, value: @room_registration.id %></p>

    <div class="booking">
      <%= f.label :start_date, "開始日", class:"bold" %><br>
      <%= f.date_field :start_date, class:"input_field" %>
    </div> 
    <div class="booking">
      <%= f.label :end_date, "終了日", class:"bold" %><br>
      <%= f.date_field :end_date, class:"input_field" %>
    </div>
    <div class="booking">
      <%= f.label :number_of_people, "人数", class:"bold" %><br>
      <%= f.number_field :number_of_people, class:"input_field", placeholder: "宿泊人数を入力"  %>
    </div>
    <div class="booking">
      <div class="submit"><%= f.submit "予約する" %></div>
      <div class="room_bookings_path"><%= link_to "宿泊施設一覧に戻る", room_bookings_path %></div>
    </div>
  <% end %>

</div>

app/views/room_bookings/confirm.html.erb
<div class="booking_container">
  <h3>予約確認画面</h3>

  <div class="booking">
    <p>金額</p>
    <p>¥<%= @room_booking.room_registration.room_price %>（お１人様１泊につき）</p>
  </div>
  <div class="booking">
    <p>開始日</p>
    <p><%= @room_booking.start_date %></p>
  </div>
  <div class="booking">
    <p>終了日</p>
    <p><%= @room_booking.end_date %></p>
  </div>
  <div class="booking">
    <p>滞在日数</p>
    <p><%= @booking_days %>泊<%= @booking_days + 1 %>日</p>
  </div>
  <div class="booking">
    <p>人数</p>
    <p><%= @room_booking.number_of_people %>人</p>
  </div>
  <div class="booking">
    <p>お支払い金額</p>
    <p><%= @room_booking.room_registration.room_price %>円/泊 × <%= @room_booking.number_of_people %>人 × <%= @booking_days %>泊</p>
    <p>¥<%= @room_booking.room_registration.room_price * @room_booking.number_of_people * @booking_days %></p>
  </div>
  
  <div class="booking">
    <p>上記内容でよろしければ「予約を確定」を押してください</p>

  <%= form_with model: @room_booking do |f| %>
    <%= f.hidden_field :room_registration_id %>
    <%= f.hidden_field :start_date %> 
    <%= f.hidden_field :end_date %>
    <%= f.hidden_field :number_of_people %>  
    <div><%= f.submit "予約を確定", class: "submit" %></div>
    <button type="button", class="btn btn-success""><%= link_to "ルーム情報一覧へ", room_registrations_path %></button> 
  <% end %>
  
</div>

app/views/room_bookings/create.html.erb
<% if notice or alert %>
    <div class="flash">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
<% end %>

<div class="booking_container">   
  <h3>予約確定画面</h3>

  <div class="booking">
    <p>開始日</p>
    <p><%= @room_booking.start_date %></p>
  </div>
  <div class="booking">
    <p>終了日</p>
    <p><%= @room_booking.end_date %></p>
  </div>
  <div class="booking">
    <p>滞在日数</p>
    <p><%= @booking_days %>泊<%= @booking_days + 1 %>日</p>
  </div>
  <div class="booking">
    <p>人数</p>
    <p><%= @room_booking.number_of_people %>人</p>
  </div>
  <div class="booking">
    <p>お支払い金額</p>
    <p><%= @room_booking.room_registration.room_price %>円/泊 × <%= @room_booking.number_of_people %>人 × <%= @booking_days %>泊</p>
    <p>¥<%= @room_booking.room_registration.room_price * @room_booking.number_of_people * @booking_days %></p>
  </div>
  <div class="booking">
    <p><%= link_to "トップへ戻る", home_index_path %></p>
  </div>
</div>
  

app/views/room_bookings/index.html.erb
<div class="booking_container">
  <h3>ルーム予約済情報一覧</h3>

  <div>
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>ユーザー名</th>
          <th>ユーザーID</th>
          <th>ルーム画像</th>
          <th>ルーム名</th>
          <th>ルーム紹介</th>
          <th>合計金額</th>
          <th>開始日</th>
          <th>終了日</th>
          <th>予約確定日時</th>
        </tr>
      </thead>
      <% @room_bookings.each do |room_booking| %>
        <tbody>
          <tr>
            <td><%= room_booking.user.name %></td>
            <td><%= room_booking.user.id %></td>
            <td><%= image_tag room_booking.room_registration.room_image.thumb300.url %></td>
            <td><%= room_booking.room_registration.room_name %></td>
            <td><%= room_booking.room_registration.room_introduction %></td>
            <td><%= room_booking.room_registration.room_price %></td>
            <td><%= room_booking.start_date %></td>
            <td><%= room_booking.end_date %></td>
            <td><%= room_booking.created_at %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/room_bookings/show.html.erb
<div class="booking_container">
  <h3><%= current_user.name %>さん のルーム予約済情報一覧</h3>

  <div class="booking_table">
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>ルーム画像</th>
          <th>ルーム名</th>
          <th>ルーム紹介</th>
          <th>金額（１人当たり）</th>
          <th>予約人数</th>
          <th>開始日</th>
          <th>終了日</th>
          <th>宿泊日数</th>
          <th>合計金額</th>
          <th>予約確定日時</th>
        </tr>
      </thead>
      <% @room_bookings.each do |room_booking| %>
      <tbody>
        <tr>
          <td><%= image_tag room_booking.room_registration.room_image.thumb300.url %></td>
          <td><%= room_booking.room_registration.room_name %></td>
          <td><%= room_booking.room_registration.room_introduction %></td>
          <td><%= room_booking.room_registration.room_price %></td>
          <td><%= room_booking.number_of_people %></td>
          <td><%= room_booking.start_date %></td>
          <td><%= room_booking.end_date %></td>
          <td><%= (room_booking.end_date - room_booking.start_date).to_i %>泊<%= (room_booking.end_date - room_booking.start_date).to_i + 1 %>日</td>
          <td><%= room_booking.room_registration.room_price * room_booking.number_of_people * (room_booking.end_date - room_booking.start_date).to_i %></td>
          <td><%= room_booking.created_at %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
</div>